import YAML from 'yaml';
import { SimpleYamlSerializer } from '../../../../../../src/org/metadatacenter/io/writer/yaml/SimpleYamlSerializer';
import { JsonNode } from '../../../../../../src/org/metadatacenter/model/cedar/types/basic-types/JsonNode';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
const fixtures: { value: string; javaYaml: string }[] = JSON.parse(readFileSync(join(__dirname, 'fixtures/java-escaped-scalars.json'), 'utf8'));

// Generated by cedar-artifact-library 214fefc1 using YamlSerializer.getYAML on a TextField
// description, with full quotes and compact=false. These retain Java's exact escape spelling.
describe('Java-compatible YAML escapes', () => {
  test.each(fixtures.map((fixture, index) => ({ ...fixture, index })))('preserves probe $index', ({ value, javaYaml }) => {
    const yaml = SimpleYamlSerializer.serialize({ description: value } as JsonNode);
    expect(yaml).toBe(javaYaml);
    expect(YAML.parse(yaml)).toEqual({ description: value });
    const keyYaml = SimpleYamlSerializer.serialize({ [value]: value } as JsonNode);
    expect(YAML.parse(keyYaml)).toEqual({ [value]: value });
  });
});
